// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;

pub enum TenantPlanOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TenantPlan<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for TenantPlan<'a> {
  type Inner = TenantPlan<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> TenantPlan<'a> {
  pub const VT_CPU_MICROS: ::flatbuffers::VOffsetT = 4;
  pub const VT_MEMORY_BYTES: ::flatbuffers::VOffsetT = 6;
  pub const VT_STORAGE_BYTES: ::flatbuffers::VOffsetT = 8;
  pub const VT_BANDWIDTH_BYTES: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    TenantPlan { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TenantPlanArgs
  ) -> ::flatbuffers::WIPOffset<TenantPlan<'bldr>> {
    let mut builder = TenantPlanBuilder::new(_fbb);
    builder.add_bandwidth_bytes(args.bandwidth_bytes);
    builder.add_storage_bytes(args.storage_bytes);
    builder.add_memory_bytes(args.memory_bytes);
    builder.add_cpu_micros(args.cpu_micros);
    builder.finish()
  }


  #[inline]
  pub fn cpu_micros(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(TenantPlan::VT_CPU_MICROS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn memory_bytes(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(TenantPlan::VT_MEMORY_BYTES, Some(0)).unwrap()}
  }
  #[inline]
  pub fn storage_bytes(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(TenantPlan::VT_STORAGE_BYTES, Some(0)).unwrap()}
  }
  #[inline]
  pub fn bandwidth_bytes(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(TenantPlan::VT_BANDWIDTH_BYTES, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for TenantPlan<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("cpu_micros", Self::VT_CPU_MICROS, false)?
     .visit_field::<u64>("memory_bytes", Self::VT_MEMORY_BYTES, false)?
     .visit_field::<u64>("storage_bytes", Self::VT_STORAGE_BYTES, false)?
     .visit_field::<u64>("bandwidth_bytes", Self::VT_BANDWIDTH_BYTES, false)?
     .finish();
    Ok(())
  }
}
pub struct TenantPlanArgs {
    pub cpu_micros: u64,
    pub memory_bytes: u64,
    pub storage_bytes: u64,
    pub bandwidth_bytes: u64,
}
impl<'a> Default for TenantPlanArgs {
  #[inline]
  fn default() -> Self {
    TenantPlanArgs {
      cpu_micros: 0,
      memory_bytes: 0,
      storage_bytes: 0,
      bandwidth_bytes: 0,
    }
  }
}

pub struct TenantPlanBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TenantPlanBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_cpu_micros(&mut self, cpu_micros: u64) {
    self.fbb_.push_slot::<u64>(TenantPlan::VT_CPU_MICROS, cpu_micros, 0);
  }
  #[inline]
  pub fn add_memory_bytes(&mut self, memory_bytes: u64) {
    self.fbb_.push_slot::<u64>(TenantPlan::VT_MEMORY_BYTES, memory_bytes, 0);
  }
  #[inline]
  pub fn add_storage_bytes(&mut self, storage_bytes: u64) {
    self.fbb_.push_slot::<u64>(TenantPlan::VT_STORAGE_BYTES, storage_bytes, 0);
  }
  #[inline]
  pub fn add_bandwidth_bytes(&mut self, bandwidth_bytes: u64) {
    self.fbb_.push_slot::<u64>(TenantPlan::VT_BANDWIDTH_BYTES, bandwidth_bytes, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TenantPlanBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TenantPlanBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<TenantPlan<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for TenantPlan<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("TenantPlan");
      ds.field("cpu_micros", &self.cpu_micros());
      ds.field("memory_bytes", &self.memory_bytes());
      ds.field("storage_bytes", &self.storage_bytes());
      ds.field("bandwidth_bytes", &self.bandwidth_bytes());
      ds.finish()
  }
}
