[package]
name = "selium-rpc"
version.workspace = true
edition.workspace = true
description = "Selium RPC pattern crate for typed request/reply communication"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
rkyv.workspace = true
selium-abi.workspace = true
selium-guest.workspace = true
thiserror.workspace = true

[lints]
workspace = true
