[package]
name = "selium-io"
version.workspace = true
edition.workspace = true
description = "Selium guest-side messaging library"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
rkyv.workspace = true
selium-abi.workspace = true
selium-guest.workspace = true

[lints]
workspace = true
