// Generated by Selium IDL compiler
use rkyv::{Archive, Deserialize, Serialize};

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct EchoRequest {
    pub correlation_id: u32,
    pub body: String,
}

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct EchoResponse {
    pub correlation_id: u32,
    pub echoed: String,
}

pub const EVENT_ECHO_REQUESTED: &str = "echo.requested";
pub const EVENT_ECHO_RESPONDED: &str = "echo.responded";
