// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum DiscoveryRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Discovery request message.
///
/// Variant tag values:
///   0 = Resolve(uri)
///   1 = Register { uri, target, root_service }
///   2 = Revoke { uri }
///   3 = ResolvePrefix(uri)
///   4 = ResolveLabels { key, value }
///   5 = ListDomains
pub struct DiscoveryRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DiscoveryRequest<'a> {
  type Inner = DiscoveryRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DiscoveryRequest<'a> {
  pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
  pub const VT_URI: ::flatbuffers::VOffsetT = 6;
  pub const VT_KEY: ::flatbuffers::VOffsetT = 8;
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 10;
  pub const VT_TARGET: ::flatbuffers::VOffsetT = 12;
  pub const VT_ROOT_SERVICE: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DiscoveryRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DiscoveryRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DiscoveryRequest<'bldr>> {
    let mut builder = DiscoveryRequestBuilder::new(_fbb);
    if let Some(x) = args.target { builder.add_target(x); }
    if let Some(x) = args.value { builder.add_value(x); }
    if let Some(x) = args.key { builder.add_key(x); }
    if let Some(x) = args.uri { builder.add_uri(x); }
    builder.add_root_service(args.root_service);
    builder.add_variant(args.variant);
    builder.finish()
  }

  pub fn unpack(&self) -> DiscoveryRequestT {
    let variant = self.variant();
    let uri = self.uri().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let key = self.key().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let value = self.value().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let target = self.target().map(|x| {
      alloc::boxed::Box::new(x.unpack())
    });
    let root_service = self.root_service();
    DiscoveryRequestT {
      variant,
      uri,
      key,
      value,
      target,
      root_service,
    }
  }

  /// Variant discriminator.
  #[inline]
  pub fn variant(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(DiscoveryRequest::VT_VARIANT, Some(0)).unwrap()}
  }
  /// URI to resolve or register (used by Resolve, ResolvePrefix, Register, Revoke variants).
  #[inline]
  pub fn uri(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DiscoveryRequest::VT_URI, None)}
  }
  /// Label key (used by the ResolveLabels variant).
  #[inline]
  pub fn key(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DiscoveryRequest::VT_KEY, None)}
  }
  /// Label value (used by the ResolveLabels variant).
  #[inline]
  pub fn value(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DiscoveryRequest::VT_VALUE, None)}
  }
  /// Target resource for registration (used by Register variant).
  #[inline]
  pub fn target(&self) -> Option<ResourceTarget<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ResourceTarget>>(DiscoveryRequest::VT_TARGET, None)}
  }
  /// Marks the registration as the tenant's root service (Register variant).
  #[inline]
  pub fn root_service(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DiscoveryRequest::VT_ROOT_SERVICE, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for DiscoveryRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("uri", Self::VT_URI, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("value", Self::VT_VALUE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ResourceTarget>>("target", Self::VT_TARGET, false)?
     .visit_field::<bool>("root_service", Self::VT_ROOT_SERVICE, false)?
     .finish();
    Ok(())
  }
}
pub struct DiscoveryRequestArgs<'a> {
    pub variant: u8,
    pub uri: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub key: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub value: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub target: Option<::flatbuffers::WIPOffset<ResourceTarget<'a>>>,
    pub root_service: bool,
}
impl<'a> Default for DiscoveryRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    DiscoveryRequestArgs {
      variant: 0,
      uri: None,
      key: None,
      value: None,
      target: None,
      root_service: false,
    }
  }
}

pub struct DiscoveryRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DiscoveryRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_variant(&mut self, variant: u8) {
    self.fbb_.push_slot::<u8>(DiscoveryRequest::VT_VARIANT, variant, 0);
  }
  #[inline]
  pub fn add_uri(&mut self, uri: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DiscoveryRequest::VT_URI, uri);
  }
  #[inline]
  pub fn add_key(&mut self, key: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DiscoveryRequest::VT_KEY, key);
  }
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DiscoveryRequest::VT_VALUE, value);
  }
  #[inline]
  pub fn add_target(&mut self, target: ::flatbuffers::WIPOffset<ResourceTarget<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ResourceTarget>>(DiscoveryRequest::VT_TARGET, target);
  }
  #[inline]
  pub fn add_root_service(&mut self, root_service: bool) {
    self.fbb_.push_slot::<bool>(DiscoveryRequest::VT_ROOT_SERVICE, root_service, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DiscoveryRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DiscoveryRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DiscoveryRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DiscoveryRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DiscoveryRequest");
      ds.field("variant", &self.variant());
      ds.field("uri", &self.uri());
      ds.field("key", &self.key());
      ds.field("value", &self.value());
      ds.field("target", &self.target());
      ds.field("root_service", &self.root_service());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct DiscoveryRequestT {
  pub variant: u8,
  pub uri: Option<alloc::string::String>,
  pub key: Option<alloc::string::String>,
  pub value: Option<alloc::string::String>,
  pub target: Option<alloc::boxed::Box<ResourceTargetT>>,
  pub root_service: bool,
}
impl Default for DiscoveryRequestT {
  fn default() -> Self {
    Self {
      variant: 0,
      uri: None,
      key: None,
      value: None,
      target: None,
      root_service: false,
    }
  }
}
impl DiscoveryRequestT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<DiscoveryRequest<'b>> {
    let variant = self.variant;
    let uri = self.uri.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let key = self.key.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let value = self.value.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let target = self.target.as_ref().map(|x|{
      x.pack(_fbb)
    });
    let root_service = self.root_service;
    DiscoveryRequest::create(_fbb, &DiscoveryRequestArgs{
      variant,
      uri,
      key,
      value,
      target,
      root_service,
    })
  }
}