// Generated by Selium IDL compiler
use rkyv::{Archive, Deserialize, Serialize};

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct InventoryAdjusted {
    pub event_id: u32,
    pub sku: String,
    pub delta: i32,
}

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct DeliveryAck {
    pub consumer: String,
    pub event_id: u32,
}

pub const EVENT_INVENTORY_ADJUSTED: &str = "inventory.adjusted";
pub const EVENT_INVENTORY_DELIVERY_ACKS: &str = "inventory.delivery_acks";
