// Generated by Selium IDL compiler
use rkyv::{Archive, Deserialize, Serialize};

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct RawOrder {
    pub order_id: u32,
    pub sku: String,
    pub quantity: u32,
}

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct ReservationRequest {
    pub order_id: u32,
    pub reservation_key: String,
    pub units: u32,
}

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct ProjectionApplied {
    pub order_id: u32,
    pub projection_key: String,
}

pub const EVENT_INGRESS_ORDERS: &str = "ingress.orders";
pub const EVENT_INVENTORY_RESERVATIONS: &str = "inventory.reservations";
pub const EVENT_PROJECTIONS_APPLIED: &str = "projections.applied";
