// Generated by Selium IDL compiler
use rkyv::{Archive, Deserialize, Serialize};

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct WorkerStatus {
    pub worker_id: u32,
    pub phase: String,
}

pub const EVENT_SUPERVISOR_WORKER_STATUS: &str = "supervisor.worker_status";
