// Generated by Selium IDL compiler
use rkyv::{Archive, Deserialize, Serialize};
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ServiceBodyMode {
    None,
    Buffered,
    Stream,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceBodyBinding {
    pub mode: ServiceBodyMode,
    pub schema: Option<&'static str>,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceFieldBinding {
    pub field: &'static str,
    pub target: &'static str,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceBinding {
    pub name: &'static str,
    pub request_schema: &'static str,
    pub response_schema: &'static str,
    pub protocol: Option<&'static str>,
    pub method: Option<&'static str>,
    pub path: Option<&'static str>,
    pub request_headers: &'static [ServiceFieldBinding],
    pub request_body: ServiceBodyBinding,
    pub response_body: ServiceBodyBinding,
}
#[derive(Debug, Clone, PartialEq, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct WorkerStatus {
    pub worker_id: u32,
    pub phase: String,
}
pub const EVENT_SUPERVISOR_WORKER_STATUS: &str = "supervisor.worker_status";
