// Generated by Selium IDL compiler
use anyhow::Context as _;
use rkyv::{Archive, Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ServiceBodyMode {
    None,
    Buffered,
    Stream,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceBodyBinding {
    pub mode: ServiceBodyMode,
    pub schema: Option<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceFieldBinding {
    pub field: &'static str,
    pub target: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceBinding {
    pub name: &'static str,
    pub request_schema: &'static str,
    pub response_schema: &'static str,
    pub protocol: Option<&'static str>,
    pub method: Option<&'static str>,
    pub path: Option<&'static str>,
    pub request_headers: &'static [ServiceFieldBinding],
    pub request_body: ServiceBodyBinding,
    pub response_body: ServiceBodyBinding,
}

#[allow(dead_code)]
fn __selium_extract_path_params(
    template: &str,
    actual: &str,
) -> Option<std::collections::BTreeMap<String, String>> {
    let template_segments = if template.trim_matches('/').is_empty() {
        Vec::new()
    } else {
        template.trim_matches('/').split('/').collect::<Vec<_>>()
    };
    let actual_segments = if actual.trim_matches('/').is_empty() {
        Vec::new()
    } else {
        actual.trim_matches('/').split('/').collect::<Vec<_>>()
    };
    if template_segments.len() != actual_segments.len() {
        return None;
    }
    let mut params = std::collections::BTreeMap::new();
    for (template_segment, actual_segment) in template_segments.into_iter().zip(actual_segments) {
        if template_segment.starts_with('{')
            && template_segment.ends_with('}')
            && template_segment.len() > 2
        {
            params.insert(
                template_segment[1..template_segment.len() - 1].to_string(),
                actual_segment.to_string(),
            );
        } else if template_segment != actual_segment {
            return None;
        }
    }
    Some(params)
}

#[allow(dead_code)]
async fn __selium_read_stream_message(
    stream: &selium_guest::network::StreamChannel,
    max_bytes: u32,
    timeout_ms: u32,
) -> anyhow::Result<Vec<u8>> {
    let mut payload = Vec::new();
    loop {
        let Some(chunk) = stream.recv(max_bytes, timeout_ms).await? else {
            continue;
        };
        payload.extend_from_slice(&chunk.bytes);
        if chunk.finish {
            return Ok(payload);
        }
    }
}

#[derive(Debug, Clone, PartialEq, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct EchoChunk {
    pub payload: Vec<u8>,
}

pub const STREAM_QUIC_ECHO: &str = "quic.echo";

#[allow(dead_code)]
pub mod quic_echo {
    use super::*;

    pub const DEF: &str = super::STREAM_QUIC_ECHO;

    pub async fn open(
        session: &selium_guest::network::Session,
    ) -> anyhow::Result<Option<selium_guest::network::StreamChannel>> {
        Ok(selium_guest::network::stream::open(session).await?)
    }

    pub async fn accept(
        session: &selium_guest::network::Session,
        timeout_ms: u32,
    ) -> anyhow::Result<Option<selium_guest::network::StreamChannel>> {
        Ok(selium_guest::network::stream::accept(session, timeout_ms).await?)
    }

    pub async fn send(
        stream: &selium_guest::network::StreamChannel,
        payload: &EchoChunk,
        timeout_ms: u32,
    ) -> anyhow::Result<()> {
        stream
            .send(
                selium_abi::encode_rkyv(payload).context("encode QUIC stream payload")?,
                true,
                timeout_ms,
            )
            .await?;
        Ok(())
    }

    pub async fn recv(
        stream: &selium_guest::network::StreamChannel,
        max_bytes: u32,
        timeout_ms: u32,
    ) -> anyhow::Result<EchoChunk> {
        let payload = __selium_read_stream_message(stream, max_bytes, timeout_ms).await?;
        selium_abi::decode_rkyv::<EchoChunk>(&payload).context("decode QUIC stream payload")
    }
}
