// Generated by Selium IDL compiler
use anyhow::Context as _;
use rkyv::{Archive, Deserialize, Serialize};
#[allow(unused_imports)]
pub use selium_guest::bindings::{
    SELIUM_CONTRACT_CODEC_MAJOR_VERSION, ServiceBinding, ServiceBodyBinding, ServiceBodyMode,
    ServiceFieldBinding,
};
#[derive(Debug, Clone, PartialEq, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct EchoChunk {
    pub payload: Vec<u8>,
}
impl selium_abi::CanonicalSerialize for EchoChunk {
    fn encode_to(
        &self,
        encoder: &mut selium_abi::CanonicalEncoder,
    ) -> Result<(), selium_abi::ContractCodecError> {
        encoder.encode_value(&self.payload)?;
        Ok(())
    }
}
impl selium_abi::CanonicalDeserialize for EchoChunk {
    fn decode_from(
        decoder: &mut selium_abi::CanonicalDecoder<'_>,
    ) -> Result<Self, selium_abi::ContractCodecError> {
        Ok(Self {
            payload: decoder.decode_value()?,
        })
    }
}
pub const STREAM_QUIC_ECHO: &str = "quic.echo";
#[allow(dead_code)]
pub mod quic_echo {
    use super::*;
    pub const DEF: &str = super::STREAM_QUIC_ECHO;
    pub async fn open(
        session: &selium_guest::network::Session,
    ) -> anyhow::Result<Option<selium_guest::network::StreamChannel>> {
        Ok(selium_guest::network::stream::open(session).await?)
    }
    pub async fn accept(
        session: &selium_guest::network::Session,
        timeout_ms: u32,
    ) -> anyhow::Result<Option<selium_guest::network::StreamChannel>> {
        Ok(selium_guest::network::stream::accept(session, timeout_ms).await?)
    }
    pub async fn send(
        stream: &selium_guest::network::StreamChannel,
        payload: &EchoChunk,
        timeout_ms: u32,
    ) -> anyhow::Result<()> {
        stream
            .send(
                selium_abi::encode_canonical(payload).context("encode QUIC stream payload")?,
                true,
                timeout_ms,
            )
            .await?;
        Ok(())
    }
    pub async fn recv(
        stream: &selium_guest::network::StreamChannel,
        max_bytes: u32,
        timeout_ms: u32,
    ) -> anyhow::Result<EchoChunk> {
        let payload =
            selium_guest::bindings::read_stream_message(stream, max_bytes, timeout_ms).await?;
        selium_abi::decode_canonical::<EchoChunk>(&payload).context("decode QUIC stream payload")
    }
}
