[package]
name = "selium-bridge-guest"
version.workspace = true
edition.workspace = true
description = "Reference QUIC-to-shared-memory bridge guest"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
quinn = { workspace = true, features = ["rustls-ring"] }
selium-guest = { workspace = true, features = ["io", "quinn"] }
selium-quic = { path = "../../core/quic" }
selium-shm.workspace = true
selium-wire.workspace = true
tokio = { workspace = true, features = ["io-util"] }

[lints]
workspace = true
