// Generated by Selium IDL compiler
use rkyv::{Archive, Deserialize, Serialize};
#[allow(unused_imports)]
pub use selium_guest::bindings::{
    SELIUM_CONTRACT_CODEC_MAJOR_VERSION, ServiceBinding, ServiceBodyBinding, ServiceBodyMode,
    ServiceFieldBinding,
};
#[derive(Debug, Clone, PartialEq, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct Frame {
    pub source: String,
    pub seq: u32,
}
impl selium_abi::CanonicalSerialize for Frame {
    fn encode_to(
        &self,
        encoder: &mut selium_abi::CanonicalEncoder,
    ) -> Result<(), selium_abi::ContractCodecError> {
        encoder.encode_value(&self.source)?;
        encoder.encode_value(&self.seq)?;
        Ok(())
    }
}
impl selium_abi::CanonicalDeserialize for Frame {
    fn decode_from(
        decoder: &mut selium_abi::CanonicalDecoder<'_>,
    ) -> Result<Self, selium_abi::ContractCodecError> {
        Ok(Self {
            source: decoder.decode_value()?,
            seq: decoder.decode_value()?,
        })
    }
}
#[derive(Debug, Clone, PartialEq, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct EnrichedFrame {
    pub source: String,
    pub seq: u32,
    pub stage: String,
}
impl selium_abi::CanonicalSerialize for EnrichedFrame {
    fn encode_to(
        &self,
        encoder: &mut selium_abi::CanonicalEncoder,
    ) -> Result<(), selium_abi::ContractCodecError> {
        encoder.encode_value(&self.source)?;
        encoder.encode_value(&self.seq)?;
        encoder.encode_value(&self.stage)?;
        Ok(())
    }
}
impl selium_abi::CanonicalDeserialize for EnrichedFrame {
    fn decode_from(
        decoder: &mut selium_abi::CanonicalDecoder<'_>,
    ) -> Result<Self, selium_abi::ContractCodecError> {
        Ok(Self {
            source: decoder.decode_value()?,
            seq: decoder.decode_value()?,
            stage: decoder.decode_value()?,
        })
    }
}
pub const EVENT_INGEST_FRAMES: &str = "ingest.frames";
pub const EVENT_PROCESS_ENRICHED: &str = "process.enriched";
