// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum DiscoveryRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Discovery request message.
///
/// Variant tag values:
///   0 = Resolve(uri)
pub struct DiscoveryRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DiscoveryRequest<'a> {
  type Inner = DiscoveryRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DiscoveryRequest<'a> {
  pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
  pub const VT_URI: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DiscoveryRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DiscoveryRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DiscoveryRequest<'bldr>> {
    let mut builder = DiscoveryRequestBuilder::new(_fbb);
    if let Some(x) = args.uri { builder.add_uri(x); }
    builder.add_variant(args.variant);
    builder.finish()
  }


  /// Variant discriminator.
  #[inline]
  pub fn variant(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(DiscoveryRequest::VT_VARIANT, Some(0)).unwrap()}
  }
  /// URI to resolve (used by Resolve variant).
  #[inline]
  pub fn uri(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DiscoveryRequest::VT_URI, None)}
  }
}

impl ::flatbuffers::Verifiable for DiscoveryRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("uri", Self::VT_URI, false)?
     .finish();
    Ok(())
  }
}
pub struct DiscoveryRequestArgs<'a> {
    pub variant: u8,
    pub uri: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for DiscoveryRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    DiscoveryRequestArgs {
      variant: 0,
      uri: None,
    }
  }
}

pub struct DiscoveryRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DiscoveryRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_variant(&mut self, variant: u8) {
    self.fbb_.push_slot::<u8>(DiscoveryRequest::VT_VARIANT, variant, 0);
  }
  #[inline]
  pub fn add_uri(&mut self, uri: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DiscoveryRequest::VT_URI, uri);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DiscoveryRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DiscoveryRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DiscoveryRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DiscoveryRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DiscoveryRequest");
      ds.field("variant", &self.variant());
      ds.field("uri", &self.uri());
      ds.finish()
  }
}
