// Generated by Selium IDL compiler
use rkyv::{Archive, Deserialize, Serialize};

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct CounterDelta {
    pub seq: u32,
    pub amount: u32,
}

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct CounterCheckpoint {
    pub last_seq: u32,
    pub running_total: u32,
    pub mode: String,
}

pub const EVENT_COUNTER_DELTAS: &str = "counter.deltas";
pub const EVENT_COUNTER_CHECKPOINTS: &str = "counter.checkpoints";
