// Automatically generated by build.rs. Do not modify manually.
// Combined module tree for Selium Flatbuffers namespaces.
pub mod selium {
  use super::*;
  pub mod control {
    use super::*;
    mod resolved_target_generated;
    pub use self::resolved_target_generated::*;
    mod deployment_generated;
    pub use self::deployment_generated::*;
    mod delegation_status_generated;
    pub use self::delegation_status_generated::*;
    mod control_request_generated;
    pub use self::control_request_generated::*;
    mod control_response_generated;
    pub use self::control_response_generated::*;
    mod pipeline_binding_generated;
    pub use self::pipeline_binding_generated::*;
    mod desired_state_record_generated;
    pub use self::desired_state_record_generated::*;
  }
  pub mod discovery {
    use super::*;
    mod interface_metadata_generated;
    pub use self::interface_metadata_generated::*;
    mod label_generated;
    pub use self::label_generated::*;
    mod resource_target_generated;
    pub use self::resource_target_generated::*;
    mod domain_entry_generated;
    pub use self::domain_entry_generated::*;
    mod discovery_request_generated;
    pub use self::discovery_request_generated::*;
    mod discovery_response_generated;
    pub use self::discovery_response_generated::*;
  }
  pub mod live_table {
    use super::*;
    mod live_table_message_generated;
    pub use self::live_table_message_generated::*;
  }
  pub mod logging {
    use super::*;
    mod field_generated;
    pub use self::field_generated::*;
    mod log_level_generated;
    pub use self::log_level_generated::*;
    mod log_record_generated;
    pub use self::log_record_generated::*;
    mod span_generated;
    pub use self::span_generated::*;
  }
  pub mod pipe {
    use super::*;
    mod pipe_control_generated;
    pub use self::pipe_control_generated::*;
  }
  pub mod scheduler {
    use super::*;
    mod scheduler_generated;
    pub use self::scheduler_generated::*;
  }
}
