// Automatically generated by build.rs. Do not modify manually.
// Combined module tree for Selium Flatbuffers namespaces.
pub mod selium {
  use super::*;
  pub mod discovery {
    use super::*;
    mod discovery_request_generated;
    pub use self::discovery_request_generated::*;
    mod discovery_response_generated;
    pub use self::discovery_response_generated::*;
    mod interface_metadata_generated;
    pub use self::interface_metadata_generated::*;
    mod resource_target_generated;
    pub use self::resource_target_generated::*;
  }
  pub mod live_table {
    use super::*;
    mod live_table_message_generated;
    pub use self::live_table_message_generated::*;
  }
}
