// Generated by Selium IDL compiler
use rkyv::{Archive, Deserialize, Serialize};

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct QuoteRequest {
    pub request_id: u32,
    pub quantity: u32,
}

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct QuoteResponse {
    pub request_id: u32,
    pub worker: String,
    pub total_cents: u32,
}

pub const EVENT_PRICING_QUOTE_RESULTS: &str = "pricing.quote_results";
