// Generated by Selium IDL compiler
use rkyv::{Archive, Deserialize, Serialize};
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ServiceBodyMode {
    None,
    Buffered,
    Stream,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceBodyBinding {
    pub mode: ServiceBodyMode,
    pub schema: Option<&'static str>,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceFieldBinding {
    pub field: &'static str,
    pub target: &'static str,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceBinding {
    pub name: &'static str,
    pub request_schema: &'static str,
    pub response_schema: &'static str,
    pub protocol: Option<&'static str>,
    pub method: Option<&'static str>,
    pub path: Option<&'static str>,
    pub request_headers: &'static [ServiceFieldBinding],
    pub request_body: ServiceBodyBinding,
    pub response_body: ServiceBodyBinding,
}
pub const SELIUM_CONTRACT_CODEC_MAJOR_VERSION: u8 = selium_abi::CONTRACT_CODEC_MAJOR_VERSION;
#[allow(dead_code)]
fn __selium_extract_path_params(
    template: &str,
    actual: &str,
) -> Option<std::collections::BTreeMap<String, String>> {
    let template_segments = if template.trim_matches('/').is_empty() {
        Vec::new()
    } else {
        template.trim_matches('/').split('/').collect::<Vec<_>>()
    };
    let actual_segments = if actual.trim_matches('/').is_empty() {
        Vec::new()
    } else {
        actual.trim_matches('/').split('/').collect::<Vec<_>>()
    };
    if template_segments.len() != actual_segments.len() {
        return None;
    }
    let mut params = std::collections::BTreeMap::new();
    for (template_segment, actual_segment) in template_segments.into_iter().zip(actual_segments) {
        if template_segment.starts_with('{')
            && template_segment.ends_with('}')
            && template_segment.len() > 2
        {
            params.insert(
                template_segment[1..template_segment.len() - 1].to_string(),
                actual_segment.to_string(),
            );
        } else if template_segment != actual_segment {
            return None;
        }
    }
    Some(params)
}
#[allow(dead_code)]
async fn __selium_read_stream_message(
    stream: &selium_guest::network::StreamChannel,
    max_bytes: u32,
    timeout_ms: u32,
) -> anyhow::Result<Vec<u8>> {
    let mut payload = Vec::new();
    loop {
        let Some(chunk) = stream.recv(max_bytes, timeout_ms).await? else {
            continue;
        };
        payload.extend_from_slice(&chunk.bytes);
        if chunk.finish {
            return Ok(payload);
        }
    }
}
#[derive(Debug, Clone, PartialEq, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct QuoteRequest {
    pub request_id: u32,
    pub quantity: u32,
}
impl selium_abi::CanonicalSerialize for QuoteRequest {
    fn encode_to(
        &self,
        encoder: &mut selium_abi::CanonicalEncoder,
    ) -> Result<(), selium_abi::ContractCodecError> {
        encoder.encode_value(&self.request_id)?;
        encoder.encode_value(&self.quantity)?;
        Ok(())
    }
}
impl selium_abi::CanonicalDeserialize for QuoteRequest {
    fn decode_from(
        decoder: &mut selium_abi::CanonicalDecoder<'_>,
    ) -> Result<Self, selium_abi::ContractCodecError> {
        Ok(Self {
            request_id: decoder.decode_value()?,
            quantity: decoder.decode_value()?,
        })
    }
}
#[derive(Debug, Clone, PartialEq, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct QuoteResponse {
    pub request_id: u32,
    pub worker: String,
    pub total_cents: u32,
}
impl selium_abi::CanonicalSerialize for QuoteResponse {
    fn encode_to(
        &self,
        encoder: &mut selium_abi::CanonicalEncoder,
    ) -> Result<(), selium_abi::ContractCodecError> {
        encoder.encode_value(&self.request_id)?;
        encoder.encode_value(&self.worker)?;
        encoder.encode_value(&self.total_cents)?;
        Ok(())
    }
}
impl selium_abi::CanonicalDeserialize for QuoteResponse {
    fn decode_from(
        decoder: &mut selium_abi::CanonicalDecoder<'_>,
    ) -> Result<Self, selium_abi::ContractCodecError> {
        Ok(Self {
            request_id: decoder.decode_value()?,
            worker: decoder.decode_value()?,
            total_cents: decoder.decode_value()?,
        })
    }
}
pub const EVENT_PRICING_QUOTE_WORKER_A_REQUESTS: &str = "pricing.quote_worker_a_requests";
pub const EVENT_PRICING_QUOTE_WORKER_B_REQUESTS: &str = "pricing.quote_worker_b_requests";
pub const EVENT_PRICING_QUOTE_RESULTS: &str = "pricing.quote_results";
pub const SERVICE_QUOTE: ServiceBinding = ServiceBinding {
    name: "quote",
    request_schema: "QuoteRequest",
    response_schema: "QuoteResponse",
    protocol: None,
    method: None,
    path: None,
    request_headers: &[],
    request_body: ServiceBodyBinding {
        mode: ServiceBodyMode::Buffered,
        schema: Some("QuoteRequest"),
    },
    response_body: ServiceBodyBinding {
        mode: ServiceBodyMode::Buffered,
        schema: Some("QuoteResponse"),
    },
};
