// Generated by Selium IDL compiler
use rkyv::{Archive, Deserialize, Serialize};
#[allow(unused_imports)]
pub use selium_guest::bindings::{
    SELIUM_CONTRACT_CODEC_MAJOR_VERSION, ServiceBinding, ServiceBodyBinding, ServiceBodyMode,
    ServiceFieldBinding,
};
#[derive(Debug, Clone, PartialEq, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct QuoteRequest {
    pub request_id: u32,
    pub quantity: u32,
}
impl selium_abi::CanonicalSerialize for QuoteRequest {
    fn encode_to(
        &self,
        encoder: &mut selium_abi::CanonicalEncoder,
    ) -> Result<(), selium_abi::ContractCodecError> {
        encoder.encode_value(&self.request_id)?;
        encoder.encode_value(&self.quantity)?;
        Ok(())
    }
}
impl selium_abi::CanonicalDeserialize for QuoteRequest {
    fn decode_from(
        decoder: &mut selium_abi::CanonicalDecoder<'_>,
    ) -> Result<Self, selium_abi::ContractCodecError> {
        Ok(Self {
            request_id: decoder.decode_value()?,
            quantity: decoder.decode_value()?,
        })
    }
}
#[derive(Debug, Clone, PartialEq, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct QuoteResponse {
    pub request_id: u32,
    pub worker: String,
    pub total_cents: u32,
}
impl selium_abi::CanonicalSerialize for QuoteResponse {
    fn encode_to(
        &self,
        encoder: &mut selium_abi::CanonicalEncoder,
    ) -> Result<(), selium_abi::ContractCodecError> {
        encoder.encode_value(&self.request_id)?;
        encoder.encode_value(&self.worker)?;
        encoder.encode_value(&self.total_cents)?;
        Ok(())
    }
}
impl selium_abi::CanonicalDeserialize for QuoteResponse {
    fn decode_from(
        decoder: &mut selium_abi::CanonicalDecoder<'_>,
    ) -> Result<Self, selium_abi::ContractCodecError> {
        Ok(Self {
            request_id: decoder.decode_value()?,
            worker: decoder.decode_value()?,
            total_cents: decoder.decode_value()?,
        })
    }
}
pub const EVENT_PRICING_QUOTE_WORKER_A_REQUESTS: &str = "pricing.quote_worker_a_requests";
pub const EVENT_PRICING_QUOTE_WORKER_B_REQUESTS: &str = "pricing.quote_worker_b_requests";
pub const EVENT_PRICING_QUOTE_RESULTS: &str = "pricing.quote_results";
pub const SERVICE_QUOTE: ServiceBinding = ServiceBinding {
    name: "quote",
    request_schema: "QuoteRequest",
    response_schema: "QuoteResponse",
    protocol: None,
    method: None,
    path: None,
    request_headers: &[],
    request_body: ServiceBodyBinding {
        mode: ServiceBodyMode::Buffered,
        schema: Some("QuoteRequest"),
    },
    response_body: ServiceBodyBinding {
        mode: ServiceBodyMode::Buffered,
        schema: Some("QuoteResponse"),
    },
};
