// Generated by Selium IDL compiler
use rkyv::{Archive, Deserialize, Serialize};

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct Frame {
    pub source: String,
    pub seq: u32,
}

#[derive(Debug, Clone, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct EnrichedFrame {
    pub source: String,
    pub seq: u32,
    pub stage: String,
}

pub const EVENT_INGEST_FRAMES: &str = "ingest.frames";
pub const EVENT_PROCESS_ENRICHED: &str = "process.enriched";
