// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum DiscoveryResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Discovery response message.
///
/// Variant tag values:
///   0 = Found(target)
///   1 = NotFound
///   2 = Registered
///   3 = Revoked
///   4 = Forbidden
pub struct DiscoveryResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DiscoveryResponse<'a> {
  type Inner = DiscoveryResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DiscoveryResponse<'a> {
  pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
  pub const VT_TARGET: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DiscoveryResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DiscoveryResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DiscoveryResponse<'bldr>> {
    let mut builder = DiscoveryResponseBuilder::new(_fbb);
    if let Some(x) = args.target { builder.add_target(x); }
    builder.add_variant(args.variant);
    builder.finish()
  }


  /// Variant discriminator.
  #[inline]
  pub fn variant(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(DiscoveryResponse::VT_VARIANT, Some(0)).unwrap()}
  }
  /// The discovered resource (used by Found variant).
  #[inline]
  pub fn target(&self) -> Option<ResourceTarget<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ResourceTarget>>(DiscoveryResponse::VT_TARGET, None)}
  }
}

impl ::flatbuffers::Verifiable for DiscoveryResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ResourceTarget>>("target", Self::VT_TARGET, false)?
     .finish();
    Ok(())
  }
}
pub struct DiscoveryResponseArgs<'a> {
    pub variant: u8,
    pub target: Option<::flatbuffers::WIPOffset<ResourceTarget<'a>>>,
}
impl<'a> Default for DiscoveryResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    DiscoveryResponseArgs {
      variant: 0,
      target: None,
    }
  }
}

pub struct DiscoveryResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DiscoveryResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_variant(&mut self, variant: u8) {
    self.fbb_.push_slot::<u8>(DiscoveryResponse::VT_VARIANT, variant, 0);
  }
  #[inline]
  pub fn add_target(&mut self, target: ::flatbuffers::WIPOffset<ResourceTarget<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ResourceTarget>>(DiscoveryResponse::VT_TARGET, target);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DiscoveryResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DiscoveryResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DiscoveryResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DiscoveryResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DiscoveryResponse");
      ds.field("variant", &self.variant());
      ds.field("target", &self.target());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `DiscoveryResponse`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_discovery_response_unchecked`.
pub fn root_as_discovery_response(buf: &[u8]) -> Result<DiscoveryResponse<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<DiscoveryResponse>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `DiscoveryResponse` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_discovery_response_unchecked`.
pub fn size_prefixed_root_as_discovery_response(buf: &[u8]) -> Result<DiscoveryResponse<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<DiscoveryResponse>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `DiscoveryResponse` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_discovery_response_unchecked`.
pub fn root_as_discovery_response_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<DiscoveryResponse<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<DiscoveryResponse<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `DiscoveryResponse` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_discovery_response_unchecked`.
pub fn size_prefixed_root_as_discovery_response_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<DiscoveryResponse<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<DiscoveryResponse<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a DiscoveryResponse and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `DiscoveryResponse`.
pub unsafe fn root_as_discovery_response_unchecked(buf: &[u8]) -> DiscoveryResponse<'_> {
  unsafe { ::flatbuffers::root_unchecked::<DiscoveryResponse>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed DiscoveryResponse and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `DiscoveryResponse`.
pub unsafe fn size_prefixed_root_as_discovery_response_unchecked(buf: &[u8]) -> DiscoveryResponse<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<DiscoveryResponse>(buf) }
}
#[inline]
pub fn finish_discovery_response_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<DiscoveryResponse<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_discovery_response_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<DiscoveryResponse<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
