mod shared;
mod transports;

use proc_macro2::TokenStream;
use quote::quote;

use crate::ContractPackage;

use self::shared::{event_const_tokens, schema_tokens, service_const_tokens, stream_const_tokens};
use self::transports::{
    generate_http_service_module, generate_quic_service_module, generate_stream_module,
};

pub fn generate_rust_bindings(package: &ContractPackage) -> String {
    let file = syn::parse2::<syn::File>(generate_rust_bindings_tokens(package))
        .expect("generated Selium bindings should parse as Rust");
    format!(
        "// Generated by Selium IDL compiler\n{}",
        prettyplease::unparse(&file)
    )
}

fn generate_rust_bindings_tokens(package: &ContractPackage) -> TokenStream {
    let needs_context_import = package
        .services
        .iter()
        .any(|service| matches!(service.protocol.as_deref(), Some("http") | Some("quic")))
        || !package.streams.is_empty();
    let context_import = if needs_context_import {
        quote!(
            use anyhow::Context as _;
        )
    } else {
        TokenStream::new()
    };
    let schemas = package.schemas.iter().map(schema_tokens);
    let events = package.events.iter().map(event_const_tokens);
    let services = package.services.iter().map(service_const_tokens);
    let streams = package.streams.iter().map(stream_const_tokens);
    let transport_modules =
        package
            .services
            .iter()
            .filter_map(|service| match service.protocol.as_deref() {
                Some("http") => Some(generate_http_service_module(package, service)),
                Some("quic") => Some(generate_quic_service_module(service)),
                _ => None,
            });
    let stream_modules = package.streams.iter().map(generate_stream_module);

    quote! {
        #context_import
        #[allow(unused_imports)]
        pub use selium_guest::bindings::{
            ServiceBinding, ServiceBodyBinding, ServiceBodyMode, ServiceFieldBinding,
            SELIUM_CONTRACT_CODEC_MAJOR_VERSION,
        };
        use rkyv::{Archive, Deserialize, Serialize};

        #(#schemas)*
        #(#events)*
        #(#services)*
        #(#streams)*
        #(#transport_modules)*
        #(#stream_modules)*
    }
}

#[cfg(test)]
mod tests {
    use crate::{ContractPackage, DeliveryGuarantee, EventDef, SchemaDef, SchemaField};

    use super::generate_rust_bindings_tokens;

    #[test]
    fn generated_tokens_parse_as_a_rust_file() {
        let package = ContractPackage {
            package: "media.pipeline.v1".to_string(),
            namespace: "media.pipeline".to_string(),
            version: "v1".to_string(),
            schemas: vec![SchemaDef {
                name: "Frame".to_string(),
                fields: vec![SchemaField {
                    name: "camera_id".to_string(),
                    ty: "string".to_string(),
                }],
            }],
            events: vec![EventDef {
                name: "camera.frames".to_string(),
                payload_schema: "Frame".to_string(),
                partitions: 1,
                retention: "24h".to_string(),
                delivery: DeliveryGuarantee::AtLeastOnce,
                replay_enabled: true,
            }],
            services: Vec::new(),
            streams: Vec::new(),
        };

        syn::parse2::<syn::File>(generate_rust_bindings_tokens(&package)).expect("parse tokens");
    }
}
