[package]
name = "selium-discovery-probe"
version.workspace = true
edition.workspace = true
description = "Discovery probe test fixture guest"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
selium-guest.workspace = true
selium-shm.workspace = true
selium-wire.workspace = true

[lints]
workspace = true
