// Generated by Selium IDL compiler
use anyhow::Context as _;
use rkyv::{Archive, Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ServiceBodyMode {
    None,
    Buffered,
    Stream,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceBodyBinding {
    pub mode: ServiceBodyMode,
    pub schema: Option<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceFieldBinding {
    pub field: &'static str,
    pub target: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceBinding {
    pub name: &'static str,
    pub request_schema: &'static str,
    pub response_schema: &'static str,
    pub protocol: Option<&'static str>,
    pub method: Option<&'static str>,
    pub path: Option<&'static str>,
    pub request_headers: &'static [ServiceFieldBinding],
    pub request_body: ServiceBodyBinding,
    pub response_body: ServiceBodyBinding,
}

#[allow(dead_code)]
fn __selium_extract_path_params(
    template: &str,
    actual: &str,
) -> Option<std::collections::BTreeMap<String, String>> {
    let template_segments = if template.trim_matches('/').is_empty() {
        Vec::new()
    } else {
        template.trim_matches('/').split('/').collect::<Vec<_>>()
    };
    let actual_segments = if actual.trim_matches('/').is_empty() {
        Vec::new()
    } else {
        actual.trim_matches('/').split('/').collect::<Vec<_>>()
    };
    if template_segments.len() != actual_segments.len() {
        return None;
    }
    let mut params = std::collections::BTreeMap::new();
    for (template_segment, actual_segment) in template_segments.into_iter().zip(actual_segments) {
        if template_segment.starts_with('{')
            && template_segment.ends_with('}')
            && template_segment.len() > 2
        {
            params.insert(
                template_segment[1..template_segment.len() - 1].to_string(),
                actual_segment.to_string(),
            );
        } else if template_segment != actual_segment {
            return None;
        }
    }
    Some(params)
}

#[allow(dead_code)]
async fn __selium_read_stream_message(
    stream: &selium_guest::network::StreamChannel,
    max_bytes: u32,
    timeout_ms: u32,
) -> anyhow::Result<Vec<u8>> {
    let mut payload = Vec::new();
    loop {
        let Some(chunk) = stream.recv(max_bytes, timeout_ms).await? else {
            continue;
        };
        payload.extend_from_slice(&chunk.bytes);
        if chunk.finish {
            return Ok(payload);
        }
    }
}

#[derive(Debug, Clone, PartialEq, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct UploadRequest {
    pub file_name: String,
    pub content_type: String,
}

#[derive(Debug, Clone, PartialEq, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct UploadReceipt {
    pub file_name: String,
    pub bytes_received: u64,
}

pub const SERVICE_UPLOAD: ServiceBinding = ServiceBinding {
    name: "upload",
    request_schema: "UploadRequest",
    response_schema: "UploadReceipt",
    protocol: Some("http"),
    method: Some("POST"),
    path: Some("/upload/{file_name}"),
    request_headers: &[ServiceFieldBinding {
        field: "content_type",
        target: "content-type",
    }],
    request_body: ServiceBodyBinding {
        mode: ServiceBodyMode::Stream,
        schema: Some("bytes"),
    },
    response_body: ServiceBodyBinding {
        mode: ServiceBodyMode::Buffered,
        schema: Some("UploadReceipt"),
    },
};

#[allow(dead_code)]
pub mod upload {
    use super::*;

    pub const DEF: ServiceBinding = super::SERVICE_UPLOAD;

    pub struct Client<'a> {
        session: &'a selium_guest::network::Session,
    }

    pub struct PendingRequest {
        exchange: selium_guest::network::ClientExchange,
        request_body: selium_guest::network::BodyWriter,
    }

    pub struct Response {
        pub head: selium_abi::NetworkRpcResponseHead,
        pub body: selium_guest::network::BodyReader,
    }

    pub struct AcceptedRequest {
        exchange: selium_guest::network::ServerExchange,
        request: UploadRequest,
    }

    impl<'a> Client<'a> {
        pub fn new(session: &'a selium_guest::network::Session) -> Self {
            Self { session }
        }

        pub async fn start(
            &self,
            request: &UploadRequest,
            timeout_ms: u32,
        ) -> anyhow::Result<Option<PendingRequest>> {
            let request_head = build_request_head(request)?;
            Ok(
                selium_guest::network::rpc::start(self.session, request_head, timeout_ms)
                    .await?
                    .map(|(exchange, request_body)| PendingRequest {
                        exchange,
                        request_body,
                    }),
            )
        }
    }

    impl PendingRequest {
        pub fn request_body(&self) -> &selium_guest::network::BodyWriter {
            &self.request_body
        }

        pub async fn await_response(self, timeout_ms: u32) -> anyhow::Result<Option<Response>> {
            Ok(self
                .exchange
                .await_response(timeout_ms)
                .await?
                .map(|(head, body)| Response { head, body }))
        }

        pub async fn await_buffered_response(
            self,
            max_bytes: u32,
            timeout_ms: u32,
        ) -> anyhow::Result<Option<UploadReceipt>> {
            match self.await_response(timeout_ms).await? {
                Some(response) => Ok(Some(response.decode_buffered(max_bytes, timeout_ms).await?)),
                None => Ok(None),
            }
        }
    }

    impl Response {
        pub async fn decode_buffered(
            self,
            max_bytes: u32,
            timeout_ms: u32,
        ) -> anyhow::Result<UploadReceipt> {
            let body = self.body.read_all(max_bytes, timeout_ms).await?;
            selium_abi::decode_rkyv::<UploadReceipt>(&body).context("decode buffered response body")
        }
    }

    pub async fn accept(
        session: &selium_guest::network::Session,
        timeout_ms: u32,
    ) -> anyhow::Result<Option<AcceptedRequest>> {
        let Some(exchange) = selium_guest::network::rpc::accept(session, timeout_ms).await? else {
            return Ok(None);
        };
        let request = parse_request_head(exchange.request_head())?;
        Ok(Some(AcceptedRequest { exchange, request }))
    }

    impl AcceptedRequest {
        pub fn request(&self) -> &UploadRequest {
            &self.request
        }

        pub fn request_body(&self) -> &selium_guest::network::BodyReader {
            self.exchange.request_body()
        }

        pub async fn respond_buffered(
            self,
            response: &UploadReceipt,
            timeout_ms: u32,
        ) -> anyhow::Result<()> {
            self.exchange
                .respond(
                    selium_abi::NetworkRpcResponse {
                        head: selium_abi::NetworkRpcResponseHead {
                            status: 200,
                            metadata: std::collections::BTreeMap::new(),
                        },
                        body: selium_abi::encode_rkyv(response)
                            .context("encode buffered response body")?,
                    },
                    timeout_ms,
                )
                .await?;
            Ok(())
        }
    }

    fn build_request_head(
        request: &UploadRequest,
    ) -> anyhow::Result<selium_abi::NetworkRpcRequestHead> {
        let mut path = "/upload/{file_name}".to_string();
        path = path.replace("{file_name}", &request.file_name.clone());
        let mut metadata = std::collections::BTreeMap::new();
        metadata.insert("content-type".to_string(), request.content_type.clone());
        Ok(selium_abi::NetworkRpcRequestHead {
            method: "POST".to_string(),
            path,
            metadata,
        })
    }

    fn parse_request_head(
        head: &selium_abi::NetworkRpcRequestHead,
    ) -> anyhow::Result<UploadRequest> {
        if head.method != "POST" {
            return Err(anyhow::anyhow!(
                "unexpected HTTP method for upload: {}",
                head.method
            ));
        }
        let params = __selium_extract_path_params("/upload/{file_name}", &head.path)
            .ok_or_else(|| anyhow::anyhow!("unexpected HTTP path for upload: {}", head.path))?;
        Ok(UploadRequest {
            file_name: params
                .get("file_name")
                .ok_or_else(|| anyhow::anyhow!("missing path parameter `file_name`"))?
                .to_string(),
            content_type: head
                .metadata
                .get("content-type")
                .ok_or_else(|| anyhow::anyhow!("missing header `content-type`"))?
                .to_string(),
        })
    }
}
