// Generated by Selium IDL compiler
use rkyv::{Archive, Deserialize, Serialize};
#[allow(unused_imports)]
pub use selium_guest::bindings::{
    SELIUM_CONTRACT_CODEC_MAJOR_VERSION, ServiceBinding, ServiceBodyBinding, ServiceBodyMode,
    ServiceFieldBinding,
};
#[derive(Debug, Clone, PartialEq, Archive, Serialize, Deserialize)]
#[rkyv(bytecheck())]
pub struct LaunchRecord {
    pub service: String,
    pub retries: i32,
    pub mode: String,
}
impl selium_abi::CanonicalSerialize for LaunchRecord {
    fn encode_to(
        &self,
        encoder: &mut selium_abi::CanonicalEncoder,
    ) -> Result<(), selium_abi::ContractCodecError> {
        encoder.encode_value(&self.service)?;
        encoder.encode_value(&self.retries)?;
        encoder.encode_value(&self.mode)?;
        Ok(())
    }
}
impl selium_abi::CanonicalDeserialize for LaunchRecord {
    fn decode_from(
        decoder: &mut selium_abi::CanonicalDecoder<'_>,
    ) -> Result<Self, selium_abi::ContractCodecError> {
        Ok(Self {
            service: decoder.decode_value()?,
            retries: decoder.decode_value()?,
            mode: decoder.decode_value()?,
        })
    }
}
pub const EVENT_LAUNCH_RECORDED: &str = "launch.recorded";
