// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum ResolvedTargetOffset {}
#[derive(Copy, Clone, PartialEq)]
pub struct ResolvedTarget<'a> {
pub _tab: ::flatbuffers::Table<'a>,
}
impl<'a> ::flatbuffers::Follow<'a> for ResolvedTarget<'a> {
type Inner = ResolvedTarget<'a>;
#[inline]
unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
}
}
impl<'a> ResolvedTarget<'a> {
pub const VT_URI: ::flatbuffers::VOffsetT = 4;
pub const VT_HOST_ID: ::flatbuffers::VOffsetT = 6;
pub const VT_RESOURCE_ID: ::flatbuffers::VOffsetT = 8;
#[inline]
pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
ResolvedTarget { _tab: table }
}
#[allow(unused_mut)]
pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
_fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
args: &'args ResolvedTargetArgs<'args>
) -> ::flatbuffers::WIPOffset<ResolvedTarget<'bldr>> {
let mut builder = ResolvedTargetBuilder::new(_fbb);
builder.add_resource_id(args.resource_id);
if let Some(x) = args.host_id { builder.add_host_id(x); }
if let Some(x) = args.uri { builder.add_uri(x); }
builder.finish()
}
#[inline]
pub fn uri(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ResolvedTarget::VT_URI, None)}
}
#[inline]
pub fn host_id(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ResolvedTarget::VT_HOST_ID, None)}
}
#[inline]
pub fn resource_id(&self) -> u64 {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<u64>(ResolvedTarget::VT_RESOURCE_ID, Some(0)).unwrap()}
}
}
impl ::flatbuffers::Verifiable for ResolvedTarget<'_> {
#[inline]
fn run_verifier(
v: &mut ::flatbuffers::Verifier, pos: usize
) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
v.visit_table(pos)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("uri", Self::VT_URI, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("host_id", Self::VT_HOST_ID, false)?
 .visit_field::<u64>("resource_id", Self::VT_RESOURCE_ID, false)?
 .finish();
Ok(())
}
}
pub struct ResolvedTargetArgs<'a> {
pub uri: Option<::flatbuffers::WIPOffset<&'a str>>,
pub host_id: Option<::flatbuffers::WIPOffset<&'a str>>,
pub resource_id: u64,
}
impl<'a> Default for ResolvedTargetArgs<'a> {
#[inline]
fn default() -> Self {
ResolvedTargetArgs {
  uri: None,
  host_id: None,
  resource_id: 0,
}
}
}
pub struct ResolvedTargetBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ResolvedTargetBuilder<'a, 'b, A> {
#[inline]
pub fn add_uri(&mut self, uri: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ResolvedTarget::VT_URI, uri);
}
#[inline]
pub fn add_host_id(&mut self, host_id: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ResolvedTarget::VT_HOST_ID, host_id);
}
#[inline]
pub fn add_resource_id(&mut self, resource_id: u64) {
self.fbb_.push_slot::<u64>(ResolvedTarget::VT_RESOURCE_ID, resource_id, 0);
}
#[inline]
pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ResolvedTargetBuilder<'a, 'b, A> {
let start = _fbb.start_table();
ResolvedTargetBuilder {
  fbb_: _fbb,
  start_: start,
}
}
#[inline]
pub fn finish(self) -> ::flatbuffers::WIPOffset<ResolvedTarget<'a>> {
let o = self.fbb_.end_table(self.start_);
::flatbuffers::WIPOffset::new(o.value())
}
}
impl ::core::fmt::Debug for ResolvedTarget<'_> {
fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
let mut ds = f.debug_struct("ResolvedTarget");
  ds.field("uri", &self.uri());
  ds.field("host_id", &self.host_id());
  ds.field("resource_id", &self.resource_id());
  ds.finish()
}
}
pub enum DeploymentOffset {}
#[derive(Copy, Clone, PartialEq)]
pub struct Deployment<'a> {
pub _tab: ::flatbuffers::Table<'a>,
}
impl<'a> ::flatbuffers::Follow<'a> for Deployment<'a> {
type Inner = Deployment<'a>;
#[inline]
unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
}
}
impl<'a> Deployment<'a> {
pub const VT_WORKLOAD_ID: ::flatbuffers::VOffsetT = 4;
pub const VT_REPLICAS: ::flatbuffers::VOffsetT = 6;
pub const VT_MODULE: ::flatbuffers::VOffsetT = 8;
#[inline]
pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
Deployment { _tab: table }
}
#[allow(unused_mut)]
pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
_fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
args: &'args DeploymentArgs<'args>
) -> ::flatbuffers::WIPOffset<Deployment<'bldr>> {
let mut builder = DeploymentBuilder::new(_fbb);
if let Some(x) = args.module { builder.add_module(x); }
builder.add_replicas(args.replicas);
if let Some(x) = args.workload_id { builder.add_workload_id(x); }
builder.finish()
}
#[inline]
pub fn workload_id(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Deployment::VT_WORKLOAD_ID, None)}
}
#[inline]
pub fn replicas(&self) -> u32 {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<u32>(Deployment::VT_REPLICAS, Some(0)).unwrap()}
}
#[inline]
pub fn module(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Deployment::VT_MODULE, None)}
}
}
impl ::flatbuffers::Verifiable for Deployment<'_> {
#[inline]
fn run_verifier(
v: &mut ::flatbuffers::Verifier, pos: usize
) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
v.visit_table(pos)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("workload_id", Self::VT_WORKLOAD_ID, false)?
 .visit_field::<u32>("replicas", Self::VT_REPLICAS, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("module", Self::VT_MODULE, false)?
 .finish();
Ok(())
}
}
pub struct DeploymentArgs<'a> {
pub workload_id: Option<::flatbuffers::WIPOffset<&'a str>>,
pub replicas: u32,
pub module: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for DeploymentArgs<'a> {
#[inline]
fn default() -> Self {
DeploymentArgs {
  workload_id: None,
  replicas: 0,
  module: None,
}
}
}
pub struct DeploymentBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DeploymentBuilder<'a, 'b, A> {
#[inline]
pub fn add_workload_id(&mut self, workload_id: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Deployment::VT_WORKLOAD_ID, workload_id);
}
#[inline]
pub fn add_replicas(&mut self, replicas: u32) {
self.fbb_.push_slot::<u32>(Deployment::VT_REPLICAS, replicas, 0);
}
#[inline]
pub fn add_module(&mut self, module: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Deployment::VT_MODULE, module);
}
#[inline]
pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DeploymentBuilder<'a, 'b, A> {
let start = _fbb.start_table();
DeploymentBuilder {
  fbb_: _fbb,
  start_: start,
}
}
#[inline]
pub fn finish(self) -> ::flatbuffers::WIPOffset<Deployment<'a>> {
let o = self.fbb_.end_table(self.start_);
::flatbuffers::WIPOffset::new(o.value())
}
}
impl ::core::fmt::Debug for Deployment<'_> {
fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
let mut ds = f.debug_struct("Deployment");
  ds.field("workload_id", &self.workload_id());
  ds.field("replicas", &self.replicas());
  ds.field("module", &self.module());
  ds.finish()
}
}
pub enum ControlRequestOffset {}
#[derive(Copy, Clone, PartialEq)]
pub struct ControlRequest<'a> {
pub _tab: ::flatbuffers::Table<'a>,
}
impl<'a> ::flatbuffers::Follow<'a> for ControlRequest<'a> {
type Inner = ControlRequest<'a>;
#[inline]
unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
}
}
impl<'a> ControlRequest<'a> {
pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
pub const VT_WORKLOAD_ID: ::flatbuffers::VOffsetT = 6;
pub const VT_REPLICAS: ::flatbuffers::VOffsetT = 8;
pub const VT_MODULE: ::flatbuffers::VOffsetT = 10;
pub const VT_URI: ::flatbuffers::VOffsetT = 12;
pub const VT_MANIFEST: ::flatbuffers::VOffsetT = 14;
pub const VT_BYTES: ::flatbuffers::VOffsetT = 16;
#[inline]
pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
ControlRequest { _tab: table }
}
#[allow(unused_mut)]
pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
_fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
args: &'args ControlRequestArgs<'args>
) -> ::flatbuffers::WIPOffset<ControlRequest<'bldr>> {
let mut builder = ControlRequestBuilder::new(_fbb);
if let Some(x) = args.bytes { builder.add_bytes(x); }
if let Some(x) = args.manifest { builder.add_manifest(x); }
if let Some(x) = args.uri { builder.add_uri(x); }
if let Some(x) = args.module { builder.add_module(x); }
builder.add_replicas(args.replicas);
if let Some(x) = args.workload_id { builder.add_workload_id(x); }
builder.add_variant(args.variant);
builder.finish()
}
#[inline]
pub fn variant(&self) -> u8 {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<u8>(ControlRequest::VT_VARIANT, Some(0)).unwrap()}
}
#[inline]
pub fn workload_id(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlRequest::VT_WORKLOAD_ID, None)}
}
#[inline]
pub fn replicas(&self) -> u32 {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<u32>(ControlRequest::VT_REPLICAS, Some(0)).unwrap()}
}
#[inline]
pub fn module(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlRequest::VT_MODULE, None)}
}
#[inline]
pub fn uri(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlRequest::VT_URI, None)}
}
#[inline]
pub fn manifest(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlRequest::VT_MANIFEST, None)}
}
#[inline]
pub fn bytes(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(ControlRequest::VT_BYTES, None)}
}
}
impl ::flatbuffers::Verifiable for ControlRequest<'_> {
#[inline]
fn run_verifier(
v: &mut ::flatbuffers::Verifier, pos: usize
) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
v.visit_table(pos)?
 .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("workload_id", Self::VT_WORKLOAD_ID, false)?
 .visit_field::<u32>("replicas", Self::VT_REPLICAS, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("module", Self::VT_MODULE, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("uri", Self::VT_URI, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("manifest", Self::VT_MANIFEST, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("bytes", Self::VT_BYTES, false)?
 .finish();
Ok(())
}
}
pub struct ControlRequestArgs<'a> {
pub variant: u8,
pub workload_id: Option<::flatbuffers::WIPOffset<&'a str>>,
pub replicas: u32,
pub module: Option<::flatbuffers::WIPOffset<&'a str>>,
pub uri: Option<::flatbuffers::WIPOffset<&'a str>>,
pub manifest: Option<::flatbuffers::WIPOffset<&'a str>>,
pub bytes: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for ControlRequestArgs<'a> {
#[inline]
fn default() -> Self {
ControlRequestArgs {
  variant: 0,
  workload_id: None,
  replicas: 0,
  module: None,
  uri: None,
  manifest: None,
  bytes: None,
}
}
}
pub struct ControlRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ControlRequestBuilder<'a, 'b, A> {
#[inline]
pub fn add_variant(&mut self, variant: u8) {
self.fbb_.push_slot::<u8>(ControlRequest::VT_VARIANT, variant, 0);
}
#[inline]
pub fn add_workload_id(&mut self, workload_id: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlRequest::VT_WORKLOAD_ID, workload_id);
}
#[inline]
pub fn add_replicas(&mut self, replicas: u32) {
self.fbb_.push_slot::<u32>(ControlRequest::VT_REPLICAS, replicas, 0);
}
#[inline]
pub fn add_module(&mut self, module: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlRequest::VT_MODULE, module);
}
#[inline]
pub fn add_uri(&mut self, uri: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlRequest::VT_URI, uri);
}
#[inline]
pub fn add_manifest(&mut self, manifest: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlRequest::VT_MANIFEST, manifest);
}
#[inline]
pub fn add_bytes(&mut self, bytes: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlRequest::VT_BYTES, bytes);
}
#[inline]
pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ControlRequestBuilder<'a, 'b, A> {
let start = _fbb.start_table();
ControlRequestBuilder {
  fbb_: _fbb,
  start_: start,
}
}
#[inline]
pub fn finish(self) -> ::flatbuffers::WIPOffset<ControlRequest<'a>> {
let o = self.fbb_.end_table(self.start_);
::flatbuffers::WIPOffset::new(o.value())
}
}
impl ::core::fmt::Debug for ControlRequest<'_> {
fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
let mut ds = f.debug_struct("ControlRequest");
  ds.field("variant", &self.variant());
  ds.field("workload_id", &self.workload_id());
  ds.field("replicas", &self.replicas());
  ds.field("module", &self.module());
  ds.field("uri", &self.uri());
  ds.field("manifest", &self.manifest());
  ds.field("bytes", &self.bytes());
  ds.finish()
}
}
pub enum ControlResponseOffset {}
#[derive(Copy, Clone, PartialEq)]
pub struct ControlResponse<'a> {
pub _tab: ::flatbuffers::Table<'a>,
}
impl<'a> ::flatbuffers::Follow<'a> for ControlResponse<'a> {
type Inner = ControlResponse<'a>;
#[inline]
unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
}
}
impl<'a> ControlResponse<'a> {
pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
pub const VT_DEPLOYMENT: ::flatbuffers::VOffsetT = 6;
pub const VT_MANIFEST: ::flatbuffers::VOffsetT = 8;
pub const VT_APPLIED: ::flatbuffers::VOffsetT = 10;
pub const VT_STEP: ::flatbuffers::VOffsetT = 12;
pub const VT_CONTEXT: ::flatbuffers::VOffsetT = 14;
pub const VT_TARGET: ::flatbuffers::VOffsetT = 16;
#[inline]
pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
ControlResponse { _tab: table }
}
#[allow(unused_mut)]
pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
_fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
args: &'args ControlResponseArgs<'args>
) -> ::flatbuffers::WIPOffset<ControlResponse<'bldr>> {
let mut builder = ControlResponseBuilder::new(_fbb);
if let Some(x) = args.target { builder.add_target(x); }
if let Some(x) = args.context { builder.add_context(x); }
if let Some(x) = args.step { builder.add_step(x); }
if let Some(x) = args.manifest { builder.add_manifest(x); }
if let Some(x) = args.deployment { builder.add_deployment(x); }
builder.add_applied(args.applied);
builder.add_variant(args.variant);
builder.finish()
}
#[inline]
pub fn variant(&self) -> u8 {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<u8>(ControlResponse::VT_VARIANT, Some(0)).unwrap()}
}
#[inline]
pub fn deployment(&self) -> Option<Deployment<'a>> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Deployment>>(ControlResponse::VT_DEPLOYMENT, None)}
}
#[inline]
pub fn manifest(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlResponse::VT_MANIFEST, None)}
}
#[inline]
pub fn applied(&self) -> bool {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<bool>(ControlResponse::VT_APPLIED, Some(false)).unwrap()}
}
#[inline]
pub fn step(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlResponse::VT_STEP, None)}
}
#[inline]
pub fn context(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlResponse::VT_CONTEXT, None)}
}
#[inline]
pub fn target(&self) -> Option<ResolvedTarget<'a>> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ResolvedTarget>>(ControlResponse::VT_TARGET, None)}
}
}
impl ::flatbuffers::Verifiable for ControlResponse<'_> {
#[inline]
fn run_verifier(
v: &mut ::flatbuffers::Verifier, pos: usize
) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
v.visit_table(pos)?
 .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<Deployment>>("deployment", Self::VT_DEPLOYMENT, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("manifest", Self::VT_MANIFEST, false)?
 .visit_field::<bool>("applied", Self::VT_APPLIED, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("step", Self::VT_STEP, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("context", Self::VT_CONTEXT, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<ResolvedTarget>>("target", Self::VT_TARGET, false)?
 .finish();
Ok(())
}
}
pub struct ControlResponseArgs<'a> {
pub variant: u8,
pub deployment: Option<::flatbuffers::WIPOffset<Deployment<'a>>>,
pub manifest: Option<::flatbuffers::WIPOffset<&'a str>>,
pub applied: bool,
pub step: Option<::flatbuffers::WIPOffset<&'a str>>,
pub context: Option<::flatbuffers::WIPOffset<&'a str>>,
pub target: Option<::flatbuffers::WIPOffset<ResolvedTarget<'a>>>,
}
impl<'a> Default for ControlResponseArgs<'a> {
#[inline]
fn default() -> Self {
ControlResponseArgs {
  variant: 0,
  deployment: None,
  manifest: None,
  applied: false,
  step: None,
  context: None,
  target: None,
}
}
}
pub struct ControlResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ControlResponseBuilder<'a, 'b, A> {
#[inline]
pub fn add_variant(&mut self, variant: u8) {
self.fbb_.push_slot::<u8>(ControlResponse::VT_VARIANT, variant, 0);
}
#[inline]
pub fn add_deployment(&mut self, deployment: ::flatbuffers::WIPOffset<Deployment<'b >>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Deployment>>(ControlResponse::VT_DEPLOYMENT, deployment);
}
#[inline]
pub fn add_manifest(&mut self, manifest: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlResponse::VT_MANIFEST, manifest);
}
#[inline]
pub fn add_applied(&mut self, applied: bool) {
self.fbb_.push_slot::<bool>(ControlResponse::VT_APPLIED, applied, false);
}
#[inline]
pub fn add_step(&mut self, step: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlResponse::VT_STEP, step);
}
#[inline]
pub fn add_context(&mut self, context: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlResponse::VT_CONTEXT, context);
}
#[inline]
pub fn add_target(&mut self, target: ::flatbuffers::WIPOffset<ResolvedTarget<'b >>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ResolvedTarget>>(ControlResponse::VT_TARGET, target);
}
#[inline]
pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ControlResponseBuilder<'a, 'b, A> {
let start = _fbb.start_table();
ControlResponseBuilder {
  fbb_: _fbb,
  start_: start,
}
}
#[inline]
pub fn finish(self) -> ::flatbuffers::WIPOffset<ControlResponse<'a>> {
let o = self.fbb_.end_table(self.start_);
::flatbuffers::WIPOffset::new(o.value())
}
}
impl ::core::fmt::Debug for ControlResponse<'_> {
fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
let mut ds = f.debug_struct("ControlResponse");
  ds.field("variant", &self.variant());
  ds.field("deployment", &self.deployment());
  ds.field("manifest", &self.manifest());
  ds.field("applied", &self.applied());
  ds.field("step", &self.step());
  ds.field("context", &self.context());
  ds.field("target", &self.target());
  ds.finish()
}
}
#[inline]
/// Verifies that a buffer of bytes contains a `ControlRequest`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_control_request_unchecked`.
pub fn root_as_control_request(buf: &[u8]) -> Result<ControlRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
::flatbuffers::root::<ControlRequest>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `ControlRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_control_request_unchecked`.
pub fn size_prefixed_root_as_control_request(buf: &[u8]) -> Result<ControlRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
::flatbuffers::size_prefixed_root::<ControlRequest>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `ControlRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_control_request_unchecked`.
pub fn root_as_control_request_with_opts<'b, 'o>(
opts: &'o ::flatbuffers::VerifierOptions,
buf: &'b [u8],
) -> Result<ControlRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
::flatbuffers::root_with_opts::<ControlRequest<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `ControlRequest` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_control_request_unchecked`.
pub fn size_prefixed_root_as_control_request_with_opts<'b, 'o>(
opts: &'o ::flatbuffers::VerifierOptions,
buf: &'b [u8],
) -> Result<ControlRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
::flatbuffers::size_prefixed_root_with_opts::<ControlRequest<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a ControlRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `ControlRequest`.
pub unsafe fn root_as_control_request_unchecked(buf: &[u8]) -> ControlRequest<'_> {
unsafe { ::flatbuffers::root_unchecked::<ControlRequest>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed ControlRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `ControlRequest`.
pub unsafe fn size_prefixed_root_as_control_request_unchecked(buf: &[u8]) -> ControlRequest<'_> {
unsafe { ::flatbuffers::size_prefixed_root_unchecked::<ControlRequest>(buf) }
}
#[inline]
pub fn finish_control_request_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
root: ::flatbuffers::WIPOffset<ControlRequest<'a>>) {
fbb.finish(root, None);
}
#[inline]
pub fn finish_size_prefixed_control_request_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<ControlRequest<'a>>) {
fbb.finish_size_prefixed(root, None);
}
